// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACol: typeof import('ant-design-vue/es')['Col']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ARow: typeof import('ant-design-vue/es')['Row']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    Avatar: typeof import('./src/components/avatar/index.vue')['default']
    Check: typeof import('./src/components/modal/check.vue')['default']
    EditModal: typeof import('./src/components/modal/editModal.vue')['default']
    Footer: typeof import('./src/components/footer/index.vue')['default']
    Forget: typeof import('./src/components/login/forget.vue')['default']
    Header: typeof import('./src/components/header/index.vue')['default']
    Info: typeof import('./src/components/infoTips/info.vue')['default']
    InfoTips: typeof import('./src/components/infoTips/index.vue')['default']
    Layout: typeof import('./src/components/Layout/index.vue')['default']
    List: typeof import('./src/components/list/index.vue')['default']
    Login: typeof import('./src/components/login/login.vue')['default']
    Publogin: typeof import('./src/components/login/publogin.vue')['default']
    PushModal: typeof import('./src/components/modal/pushModal.vue')['default']
    Register: typeof import('./src/components/login/register.vue')['default']
    SubModal: typeof import('./src/components/modal/subModal.vue')['default']
    Title: typeof import('./src/components/title/index.vue')['default']
    WeChatModal: typeof import('./src/components/modal/weChatModal.vue')['default']
  }
}

export { }
